openapi: 3.0.3

info:
  title:  Backend APIs
  description: REST APIs 
  version: 0.0.1

servers:
  - url: http://localhost:3000/api 
    description: Local server

paths:
  /user/register:
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        description: User object
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  minLength: 2
                  maxLength: 40
                email:
                  type: string
                  format: email
                mobileNumber:
                  type: string
                  pattern: "^[0-9]+$"
                  maxLength: 10
                  minLength: 10
                password:
                  type: string
                  format: password
                confirmPassword:
                  type: string
                  format: password
              required:
                - name
                - email
                - mobileNumber
                - password
                - confirmPassword
      responses:
        "200":
          description: User is registered successfully
        "403":
          description: Email already exists

  /user/login:
    post:
      tags:
        - user
      summary: User login
      requestBody:
        description: User login with email and password
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        "200":
          description: User logs in successfully
        "401":
          description: Authentiation failed